package shoppinglist.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import shoppinglist.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.22 11:44:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikkeetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTied78 
   * @throws SailoException when error
   */
  @Test
  public void testLueTied78() throws SailoException {    // Liikkeet: 78
    Liikkeet liikkeet = new Liikkeet(); 
    Liike liike1 = new Liike(), liike2 = new Liike(); 
    liike1.tayta("1"); 
    liike2.tayta("2"); 
    String hakemisto = "testiliikkeet"; 
    String tiedNimi = hakemisto+"/nimet"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    liikkeet.lueTied(tiedNimi); 
    fail("Liikkeet: 92 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    liikkeet.lisaa(liike1); 
    liikkeet.lisaa(liike2); 
    liikkeet.tallenna("Liikkeet"); 
    liikkeet = new Liikkeet();  // Poistetaan vanhat luomalla uusi
    liikkeet.lueTied("Liikkeet");  // johon ladataan tiedot tiedostosta.
    liikkeet.lisaa(liike1); 
    liikkeet.tallenna("Liikkeet"); 
  } // Generated by ComTest END
}