package shoppinglist.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import shoppinglist.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 19:01:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ShoppingListTest {



  // Generated by ComTest BEGIN
  /** testPoistaTuote169 */
  @Test
  public void testPoistaTuote169() {    // ShoppingList: 169
    Liike citymarket = new Liike(); 
    Liike prisma = new Liike(); 
    citymarket.rekisteroi(); 
    citymarket.tayta("Citymarket"); 
    prisma.rekisteroi(); 
    prisma.tayta("Prisma"); 
  } // Generated by ComTest END
}